version: '3.7'
services:
  database:
    container_name: stocknostic-database-container
    image: postgres:14.0
    restart: always
    ports:
      - 27017:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stocknostic-database-volume:/var/lib/postgresql/data

volumes:
  stocknostic-database-volume:
